# Generated by Django 3.0.6 on 2020-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
