# Generated by Django 3.0.6 on 2020-06-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='social_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
