# Generated by Django 3.0.6 on 2020-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncup',
            name='last_device',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
