# Generated by Django 3.0.6 on 2020-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncUp', '0002_auto_20200617_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncup',
            name='last_device',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
