# Generated by Django 3.0.6 on 2020-06-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='permanent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='verses_learned',
            name='learned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='verses_learned',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='verses_marked',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
