# Generated by Django 3.0.6 on 2020-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0002_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='permanent',
            field=models.IntegerField(default=0),
        ),
    ]
