# Generated by Django 3.0.6 on 2020-06-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0003_auto_20200605_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='_id',
            new_name='label_id',
        ),
    ]
