# Generated by Django 3.0.6 on 2020-06-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0004_auto_20200605_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label_id',
            new_name='_id',
        ),
    ]
