# Generated by Django 3.0.6 on 2020-06-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0004_auto_20200618_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
