# Generated by Django 3.0.6 on 2020-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIS', '0005_auto_20200619_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verses_learned',
            name='_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verses_learned',
            name='label_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verses_marked',
            name='_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verses_marked',
            name='label_id',
            field=models.CharField(max_length=200),
        ),
    ]
