# Generated by Django 3.0.6 on 2020-07-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestAPIS', '0006_auto_20200630_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=200)),
                ('label_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('date_created', models.CharField(max_length=200)),
                ('date_updated', models.CharField(max_length=200)),
                ('state', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
